USE [master]
GO
/****** Object:  Database [EmpresaDB]    Script Date: 14/11/2025 14:16:51 ******/
CREATE DATABASE [EmpresaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmpresaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmpresaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmpresaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmpresaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [EmpresaDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmpresaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EmpresaDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EmpresaDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EmpresaDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EmpresaDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EmpresaDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [EmpresaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EmpresaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EmpresaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EmpresaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EmpresaDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EmpresaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EmpresaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EmpresaDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EmpresaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EmpresaDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [EmpresaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EmpresaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EmpresaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EmpresaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EmpresaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EmpresaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EmpresaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EmpresaDB] SET RECOVERY FULL 
GO
ALTER DATABASE [EmpresaDB] SET  MULTI_USER 
GO
ALTER DATABASE [EmpresaDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EmpresaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EmpresaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EmpresaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EmpresaDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EmpresaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EmpresaDB', N'ON'
GO
ALTER DATABASE [EmpresaDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [EmpresaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [EmpresaDB]
GO
/****** Object:  Table [dbo].[empleados]    Script Date: 14/11/2025 14:16:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[empleados](
	[idempleado] [int] NOT NULL,
	[apellido] [varchar](50) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[direccion] [varchar](100) NOT NULL,
	[email] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idempleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[empleados] ([idempleado], [apellido], [nombre], [direccion], [email]) VALUES (111, N'Juan', N'Lopera', N'Cr 41', N'juan@gmail.com')
GO
INSERT [dbo].[empleados] ([idempleado], [apellido], [nombre], [direccion], [email]) VALUES (222, N'Roldan', N'Eliecer', N'Cra 2 #1-1', N're@gmail.com')
GO
INSERT [dbo].[empleados] ([idempleado], [apellido], [nombre], [direccion], [email]) VALUES (333, N'Perez', N'Diego', N'Cra 3 #1-1', N'pd@gmail.com')
GO
INSERT [dbo].[empleados] ([idempleado], [apellido], [nombre], [direccion], [email]) VALUES (444, N'Ochoa', N'Leo', N'Cra 5 #1-1', N'ol@gmail.com')
GO
INSERT [dbo].[empleados] ([idempleado], [apellido], [nombre], [direccion], [email]) VALUES (555, N'Roa', N'Ana', N'Cra 6 #1-1', N'ra@gmail.com')
GO
USE [master]
GO
ALTER DATABASE [EmpresaDB] SET  READ_WRITE 
GO
